# 异常处理
// 错误出现的时机  more 错误选择器 内部调用不会被捕获吗
## 状态恢复机制
Solidity的异常处理机制使用状态恢复的方式。一旦异常产生，将撤销本次调用对于状态变量的更改，同时向调用者返回异常通知；

## 错误类型

* Error

    内置的错误类型之一，有两种类型：`Error()`和`Error(string)`；

    //重构一下
    
    该错误可以在通过reuire和revert触发；

    除了使用require触发外，合约也会根据情况主动触发Error；

* Panic

    内置的错误类型之一:`Panic(uint256)`,其中参数为错误代码;

    一个正确运行的程序不应该出现Panic异常，即使是外部输入错误；
    
    [Panic的异常代码](https://docs.soliditylang.org/zh/v0.8.17/control-structures.html#assert-require-revert-and-exceptions)

* CustomError

    自定义错误类型，定义格式为：`error CustomError(arg1,arg2);`

    自定义错误数据类型是合约的可继承属性，但不能被重写与覆盖，自定义错误只能在revert语句处触发；

## 触发方式
目前能够触发错误的语句与关键字有三种类型：Assert,Require,Revert;

|  类型   |                 触发形式                  |          错误类型           | 备注                                                                |
| :-----: | :---------------------------------------: | :-------------------------: | :------------------------------------------------------------------ |
| Assert  |             assert(condition)             |       Panic(uint256)        | assert断言适用于内部错误条件检查，一个正确的程序不应该出现Panic错误 |
| Require |        require(condition,[string])        |  Error() or Error(string)   | 适用于外部条件检查，返回错误类型于触发形式有关                      |
| Revert  | revert CustomError(arg) or revert Error() | CustomError(arg) or Error() |                                                                     |
| Revert  |             revert([string])              |       Error([string])       |                                                                     |

>使用一个自定义错误通常比使用字符串描述更加便宜（可以使用错误名表述数据），通过使用NatSpec语法可以免费提供更多的注释；


## 捕获与处理

外部调用的异常可以使用`try`和`catch`捕获；